# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/berlin/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),berlin)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,02b627ad6e363ac4232247c2119d489a4dbee881)

endif
