# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/berlin/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),berlin)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,8dc68df57a56c4e603297e8dc06bb6f6793b47eb)

endif
